- platform: manual
  name: Allarme Casa
#  code: !secret codice_allarme
  arming_time: 30
  delay_time: 20
  trigger_time: 120
  disarmed:
    trigger_time: 0
 # triggered:
 #   pending_time: 30
  disarm_after_trigger: false