# - platform: nmap_tracker
#   hosts:
#     - !secret ip_iphone_matteo
#     - !secret ip_iphone_carlotta
#   home_interval: 10
# - platform: traccar
#   host: !secret traccar_ip
#   username: !secret traccar_username
#   password: !secret traccar_password
#   port: !secret traccar_port
#   ssl: true
#   verify_ssl: false
#   interval_seconds: 60
# - platform: bluetooth_tracker
#   interval_seconds: 5
- platform: unifi_direct
  host: !secret unifi_ap_camera
  #host: !secret unifi_ap_sala
  username: !secret username_unifi_ap
  password: !secret password_unifi_ap
  interval_seconds: 60
  consider_home: 180
  new_device_defaults:
      track_new_devices: false


- platform: unifi_direct
  host: !secret unifi_ap_sala
  username: !secret username_unifi_ap
  password: !secret password_unifi_ap
  interval_seconds: 60
  consider_home: 180
  new_device_defaults:
      track_new_devices: false