- platform: switch
  name: "Dario Camera"
  entity_id: switch.shellycamera

- platform: switch
  name: "Dario Sala"
  entity_id: switch.shelly_dario_sala

- platform: switch
  name: "Faretti"
  entity_id: switch.shelly_faretti

- platform: group
  name: Hue Sala
  entities:
    - light.gina
    - light.tolomeo
    - light.led_cucina

- platform: group
  name: Luci di Natale
  entities:
    - light.rami
    - light.albero

- platform: group
  name: camera
  entities:
    - light.dario_camera
    - light.led_camera

- platform: group
  name: sala
  entities:
    - light.koogeek_ls1_2062df
    - light.luci_albero
    - light.luci_rami
    - light.dario_sala
    - light.faretti
    - light.hue_sala
    - light.led_cucina

- platform: group
  name: cucina
  entities:
    - light.led_cucina