- platform: switch
  name: "Dario Camera"
  entity_id: switch.dario_camera

- platform: switch
  name: "Dario Sala"
  entity_id: switch.dario_sala

- platform: switch
  name: "Faretti"
  entity_id: switch.faretti

- platform: group
  name: Sala
  entities:
    - light.gina
    - light.tolomeo
    - light.led_tv
    - light.rami
    - light.dario_sala
- platform: group
  name: Cucina
  entities:
    - light.led_cucina
    - light.faretti

- platform: group
  name: Luci di Natale
  entities:
    - light.rami
    - light.albero

- platform: group
  name: camera
  entities:
    - light.dario_camera
    - light.led_camera
