#resources: !include_dir_list lovelace/resources
custom_header:
  compact_mode: true
preload:
  - conditional

title: Upcoming
views:
  #- !include lovelace/views/01_principale.yaml
  #- !include lovelace/views/02_allarme.yaml
  #- !include lovelace/views/03_luci.yaml
  #- !include lovelace/views/04_prese.yaml
  #- !include lovelace/views/05_riscaldamento.yaml
  - !include lovelace/views/06_upcoming.yaml
  #- !include lovelace/views/07_plex.yaml
  #- !include lovelace/views/08_monitoring.yaml
