- platform: template
  sensors:
    ultimo_backup:
      value_template: >-
        {{ as_timestamp(state_attr('sensor.snapshot_backup', 'last_snapshot'),0 ) |timestamp_custom ("%d-%m-%Y")}}
        
    backup_gdrive:
      friendly_name: Backup Google Drive
      value_template: "{{state_attr('sensor.snapshot_backup','snapshots_in_google_drive')}}"
    backup_hassio:
      friendly_name: Backup su Hassio
      value_template: "{{state_attr('sensor.snapshot_backup','snapshots_in_hassio')}}"