- alias: "Spegni luci sala"
  initial_state: true
  trigger:
    - platform: mqtt
      topic: zigbee2mqtt/ikea_1/action
      payload: 'on'
  action:
    service: light.turn_off
    entity_id: light.sala
  mode: single