# pi_hole:  
#   host: !secret pihole_ip
#   location: admin
#   ssl: false
#   verify_ssl: true
#   api_key:  !secret pihole_api_key


#Input_Select
input_select:
  pihole_timer:
    name: Pihole Timer
    options:
      - Select Time
      - 00:05
      - 00:10
      - 00:15
      - 00:30
      - 00:45
      - 00:60
      - 08:00
    initial: Select Time

#Script
script:
  'pihole_timer_disabler':
    sequence:
    - data_template:
        duration: '{{states.input_select.pihole_timer.state}}'
      service: pi_hole.disable
      entity_id: switch.pi_hole

#Sensore
sensor:
  - platform: rest
    name: "PiHole Status"
    resource: !secret pihole_sensor_status
    value_template: '{{value_json.status}}'
  
  - platform: rest
    name: "PiHole Version"
    resource: !secret pihole_sensor_version
    value_template: '{{value_json.versions}}'
    json_attributes:
      - core_current
      - core_latest
      - web_current
      - web_latest
      - FTL_current
      - FTL_latest
  
  - platform: template
    sensors:
      pihole_check:
        friendly_name: "PiHole Check"
        value_template: >-
          {% set core_current = states.sensor.pihole_version.attributes["core_current"] %}
          {% set core_latest = states.sensor.pihole_version.attributes["core_latest"] %}
          {% set web_current = states.sensor.pihole_version.attributes["web_current"] %}
          {% set web_latest = states.sensor.pihole_version.attributes["web_latest"] %}
          {% set ftl_current = states.sensor.pihole_version.attributes["FTL_current"] %}
          {% set ftl_latest = states.sensor.pihole_version.attributes["FTL_latest"] %}
          {% if core_current != core_latest or web_current != web_latest or ftl_current != ftl_latest %}
            Update 
          {% else %} 
            Latest Update
          {% endif %}
        icon_template: >-
          {% if is_state("sensor.pihole_check", "Latest Update") %} 
            mdi:checkbox-marked
          {% else %}
            mdi:cloud-download
          {% endif %}

#Binary Sensor
binary_sensor:
  - platform: template
    sensors:
      pihole_enable:
        friendly_name: "Pihole Enable"
        value_template: "{{is_state('sensor.pihole_status','enabled')}}"